/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeddingsRouteImport } from './routes/weddings'
import { Route as VirtualTourRouteImport } from './routes/virtual-tour'
import { Route as SuitesVillasRouteImport } from './routes/suites-villas'
import { Route as SpaRouteImport } from './routes/spa'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as RegencyClubRouteImport } from './routes/regency-club'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as DiveCenterRouteImport } from './routes/dive-center'
import { Route as DiningRouteImport } from './routes/dining'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as BeachesRouteImport } from './routes/beaches'
import { Route as AttractionsRouteImport } from './routes/attractions'
import { Route as AccommodationRouteImport } from './routes/accommodation'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomsRoomIdRouteImport } from './routes/rooms.$roomId'

const WeddingsRoute = WeddingsRouteImport.update({
  id: '/weddings',
  path: '/weddings',
  getParentRoute: () => rootRouteImport,
} as any)
const VirtualTourRoute = VirtualTourRouteImport.update({
  id: '/virtual-tour',
  path: '/virtual-tour',
  getParentRoute: () => rootRouteImport,
} as any)
const SuitesVillasRoute = SuitesVillasRouteImport.update({
  id: '/suites-villas',
  path: '/suites-villas',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaRoute = SpaRouteImport.update({
  id: '/spa',
  path: '/spa',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const RegencyClubRoute = RegencyClubRouteImport.update({
  id: '/regency-club',
  path: '/regency-club',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const DiveCenterRoute = DiveCenterRouteImport.update({
  id: '/dive-center',
  path: '/dive-center',
  getParentRoute: () => rootRouteImport,
} as any)
const DiningRoute = DiningRouteImport.update({
  id: '/dining',
  path: '/dining',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const BeachesRoute = BeachesRouteImport.update({
  id: '/beaches',
  path: '/beaches',
  getParentRoute: () => rootRouteImport,
} as any)
const AttractionsRoute = AttractionsRouteImport.update({
  id: '/attractions',
  path: '/attractions',
  getParentRoute: () => rootRouteImport,
} as any)
const AccommodationRoute = AccommodationRouteImport.update({
  id: '/accommodation',
  path: '/accommodation',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdRoute = RoomsRoomIdRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accommodation': typeof AccommodationRoute
  '/attractions': typeof AttractionsRoute
  '/beaches': typeof BeachesRoute
  '/booking': typeof BookingRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/dining': typeof DiningRoute
  '/dive-center': typeof DiveCenterRoute
  '/facilities': typeof FacilitiesRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/meetings': typeof MeetingsRoute
  '/offers': typeof OffersRoute
  '/regency-club': typeof RegencyClubRoute
  '/reviews': typeof ReviewsRoute
  '/spa': typeof SpaRoute
  '/suites-villas': typeof SuitesVillasRoute
  '/virtual-tour': typeof VirtualTourRoute
  '/weddings': typeof WeddingsRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accommodation': typeof AccommodationRoute
  '/attractions': typeof AttractionsRoute
  '/beaches': typeof BeachesRoute
  '/booking': typeof BookingRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/dining': typeof DiningRoute
  '/dive-center': typeof DiveCenterRoute
  '/facilities': typeof FacilitiesRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/meetings': typeof MeetingsRoute
  '/offers': typeof OffersRoute
  '/regency-club': typeof RegencyClubRoute
  '/reviews': typeof ReviewsRoute
  '/spa': typeof SpaRoute
  '/suites-villas': typeof SuitesVillasRoute
  '/virtual-tour': typeof VirtualTourRoute
  '/weddings': typeof WeddingsRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accommodation': typeof AccommodationRoute
  '/attractions': typeof AttractionsRoute
  '/beaches': typeof BeachesRoute
  '/booking': typeof BookingRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/dining': typeof DiningRoute
  '/dive-center': typeof DiveCenterRoute
  '/facilities': typeof FacilitiesRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/meetings': typeof MeetingsRoute
  '/offers': typeof OffersRoute
  '/regency-club': typeof RegencyClubRoute
  '/reviews': typeof ReviewsRoute
  '/spa': typeof SpaRoute
  '/suites-villas': typeof SuitesVillasRoute
  '/virtual-tour': typeof VirtualTourRoute
  '/weddings': typeof WeddingsRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accommodation'
    | '/attractions'
    | '/beaches'
    | '/booking'
    | '/careers'
    | '/contact'
    | '/dining'
    | '/dive-center'
    | '/facilities'
    | '/faqs'
    | '/gallery'
    | '/meetings'
    | '/offers'
    | '/regency-club'
    | '/reviews'
    | '/spa'
    | '/suites-villas'
    | '/virtual-tour'
    | '/weddings'
    | '/rooms/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accommodation'
    | '/attractions'
    | '/beaches'
    | '/booking'
    | '/careers'
    | '/contact'
    | '/dining'
    | '/dive-center'
    | '/facilities'
    | '/faqs'
    | '/gallery'
    | '/meetings'
    | '/offers'
    | '/regency-club'
    | '/reviews'
    | '/spa'
    | '/suites-villas'
    | '/virtual-tour'
    | '/weddings'
    | '/rooms/$roomId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accommodation'
    | '/attractions'
    | '/beaches'
    | '/booking'
    | '/careers'
    | '/contact'
    | '/dining'
    | '/dive-center'
    | '/facilities'
    | '/faqs'
    | '/gallery'
    | '/meetings'
    | '/offers'
    | '/regency-club'
    | '/reviews'
    | '/spa'
    | '/suites-villas'
    | '/virtual-tour'
    | '/weddings'
    | '/rooms/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccommodationRoute: typeof AccommodationRoute
  AttractionsRoute: typeof AttractionsRoute
  BeachesRoute: typeof BeachesRoute
  BookingRoute: typeof BookingRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  DiningRoute: typeof DiningRoute
  DiveCenterRoute: typeof DiveCenterRoute
  FacilitiesRoute: typeof FacilitiesRoute
  FaqsRoute: typeof FaqsRoute
  GalleryRoute: typeof GalleryRoute
  MeetingsRoute: typeof MeetingsRoute
  OffersRoute: typeof OffersRoute
  RegencyClubRoute: typeof RegencyClubRoute
  ReviewsRoute: typeof ReviewsRoute
  SpaRoute: typeof SpaRoute
  SuitesVillasRoute: typeof SuitesVillasRoute
  VirtualTourRoute: typeof VirtualTourRoute
  WeddingsRoute: typeof WeddingsRoute
  RoomsRoomIdRoute: typeof RoomsRoomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weddings': {
      id: '/weddings'
      path: '/weddings'
      fullPath: '/weddings'
      preLoaderRoute: typeof WeddingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/virtual-tour': {
      id: '/virtual-tour'
      path: '/virtual-tour'
      fullPath: '/virtual-tour'
      preLoaderRoute: typeof VirtualTourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suites-villas': {
      id: '/suites-villas'
      path: '/suites-villas'
      fullPath: '/suites-villas'
      preLoaderRoute: typeof SuitesVillasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spa': {
      id: '/spa'
      path: '/spa'
      fullPath: '/spa'
      preLoaderRoute: typeof SpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regency-club': {
      id: '/regency-club'
      path: '/regency-club'
      fullPath: '/regency-club'
      preLoaderRoute: typeof RegencyClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dive-center': {
      id: '/dive-center'
      path: '/dive-center'
      fullPath: '/dive-center'
      preLoaderRoute: typeof DiveCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dining': {
      id: '/dining'
      path: '/dining'
      fullPath: '/dining'
      preLoaderRoute: typeof DiningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beaches': {
      id: '/beaches'
      path: '/beaches'
      fullPath: '/beaches'
      preLoaderRoute: typeof BeachesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attractions': {
      id: '/attractions'
      path: '/attractions'
      fullPath: '/attractions'
      preLoaderRoute: typeof AttractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accommodation': {
      id: '/accommodation'
      path: '/accommodation'
      fullPath: '/accommodation'
      preLoaderRoute: typeof AccommodationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId': {
      id: '/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof RoomsRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccommodationRoute: AccommodationRoute,
  AttractionsRoute: AttractionsRoute,
  BeachesRoute: BeachesRoute,
  BookingRoute: BookingRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  DiningRoute: DiningRoute,
  DiveCenterRoute: DiveCenterRoute,
  FacilitiesRoute: FacilitiesRoute,
  FaqsRoute: FaqsRoute,
  GalleryRoute: GalleryRoute,
  MeetingsRoute: MeetingsRoute,
  OffersRoute: OffersRoute,
  RegencyClubRoute: RegencyClubRoute,
  ReviewsRoute: ReviewsRoute,
  SpaRoute: SpaRoute,
  SuitesVillasRoute: SuitesVillasRoute,
  VirtualTourRoute: VirtualTourRoute,
  WeddingsRoute: WeddingsRoute,
  RoomsRoomIdRoute: RoomsRoomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
